### ISSUE TITLE
Carbon Neutral positioning, 18th April

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_cloud#25]
**DESCRIPTION:**
"With TAG we have an opportunity to have a carbon offset and we should push that everywhere on grid and cloud.
This is massive, we can be the first carbon neutral cloud in the world!!!"

**DEADLINE:** 18th April

**TO DO:**

- [x] Create Carbon neutral block for cloud website (@Sacha96 @Zizaster)
- [x] Create Carbon neutral block for farming website (@Sacha96 @Zizaster)
- [x] Add Carbon Neutral blocks on cloud website: https://github.com/threefoldfoundation/www_threefold_cloud/issues/24 ( @Vilnite)
- [x] Add Carbon Neutral blocks on farming website: https://github.com/threefoldfoundation/www_threefold_farming/issues/91 (@Vilnite)
- [ ] Carbon Neutrality backed on wiki: https://github.com/threefoldfoundation/info_cloud/issues/12 (@sachaobg)

**Comment by Sacha96** [comment]
![Farming - Earth Friendly Block](https://user-images.githubusercontent.com/54844940/115038686-0c333200-9ed0-11eb-8a70-8e95519f8c31.png)
![CLOUD - Earth Friendly Block](https://user-images.githubusercontent.com/54844940/115038693-0e958c00-9ed0-11eb-8ba7-a33d902df807.png)

**Comment by Vilnite** [comment]
Carbon Neutral wiki page will be added on next sprint web_2.7.4
